CREATE TABLE IF NOT EXISTS TB_Address (
	AddressID INTEGER NOT NULL,
	AddressLine VARCHAR(150) NOT NULL,
	City VARCHAR(150) NOT NULL,
	StateProvince VARCHAR(150),
	CountryRegion VARCHAR(150) NOT NULL,
	PostalCode VARCHAR(150) NOT NULL,
	CONSTRAINT PK_Address PRIMARY KEY (AddressID)
);
