CREATE TABLE IF NOT EXISTS DM_FactSales(
    SalesOrderNumber INTEGER NOT NULL,
    SalesOrderLineNumber INTEGER NOT NULL,
    CustomerID INTEGER NOT NULL,
    ProductID INTEGER NOT NULL,
    ShipToAddressID INTEGER NOT NULL,
    BillToAddressID INTEGER NOT NULL,
    ShipmentMethod VARCHAR(150) NOT NULL,
    UnitPrice NUMERIC(10, 4) NOT NULL,
    Discount NUMERIC(10, 4),
    OrderQuantity INTEGER NOT NULL,
    OrderLineTotal NUMERIC(10, 4) NOT NULL,
    OrderLineProfit NUMERIC(10, 4) NOT NULL,
    TaxAmount NUMERIC(10, 4) NOT NULL,
    OrderLineFreightCost NUMERIC(10, 4) NOT NULL,
    OrderStatus VARCHAR(100) NOT NULL,
    OrderDate DATE NOT NULL,
    DueDate DATE NOT NULL,
    ShipDate DATE NOT NULL,
    IsLateShipment INTEGER NOT NULL,
    CONSTRAINT PK_FactSales PRIMARY KEY (SalesOrderNumber, SalesOrderLineNumber),
    CONSTRAINT FK_Customer FOREIGN KEY (CustomerID) REFERENCES DM_Customer (CustomerID),
    CONSTRAINT FK_Product FOREIGN KEY (ProductID) REFERENCES DM_Product (ProductID),
    CONSTRAINT FK_ShipToAddressID FOREIGN KEY (ShipToAddressID) REFERENCES DM_Location (AddressID),
    CONSTRAINT FK_BillToAddressID FOREIGN KEY (BillToAddressID) REFERENCES DM_Location (AddressID),
    CONSTRAINT FK_OrderDate FOREIGN KEY (OrderDate) REFERENCES DM_Time (`Date`),
    CONSTRAINT FK_DueDate FOREIGN KEY (DueDate) REFERENCES DM_Time (`Date`),
    CONSTRAINT FK_ShipDate FOREIGN KEY (ShipDate) REFERENCES DM_Time (`Date`)    
);